### ISSUE TITLE
How to add a Font Style - feature request

### ISSUE THREAD

**Issue by joomleb** [acyba/acymailing#13]
Hi guys,
Templates > Settings > Design > Family: How to add a Font Style ?

Would be good to have a way on the upcoming versions to add our Font-style (Google Noto-sans in our case)
[The only mention we can find about it is 9 years old](https://www.acyba.com/forum/5-acymailing-how-to/23596-how-can-i-add-a-custom-font-to-my-newsletter.html)

**Comment by roumilb** [comment]
It is now available in the latest version I'm closing this issue.
