### ISSUE TITLE
Dynamic text in html attributes don't work anymore

### ISSUE THREAD

**Issue by Maestro31** [acyba/acymailing#42]
Hi,

Since we switched from version 6.18.3 to version 6.19.3, replacing dynamic texts such as '{product_url}' in an html attribute no longer works.Apparently, braces are replaced by an encoded version such as '%7D' or '%7B'.

To fix the problem momentarily, I had to overwrite the helpers/mailer.php file with the older version.

Could you restore the behavior that existed before or explain to me what I might need to do differently to make it work again?

Thank you for your work.

**Comment by JeremyAcyba** [comment]
Hello,

Could you tell me precisely how to reproduce the issue? Which integration has the {product_url} dynamic text?
You inserted it in the src attribute of an <a> element?
%7D and %7B are the encoded versions of } and {. Our dtext replacing system should be able to detect these characters and replace them.

Did you develop your own integration add-on?
